git clone -- git://github.com/processone/cache_tab deps/p1_cache_tab
git clone -- git://github.com/processone/tls deps/p1_tls
git clone -- git://github.com/processone/stringprep deps/p1_stringprep
git clone -- git://github.com/processone/xml deps/p1_xml
git clone -- git://github.com/processone/p1_sip deps/esip
git clone -- git://github.com/processone/stun deps/p1_stun
git clone -- git://github.com/processone/p1_yaml deps/p1_yaml
git clone -- git://github.com/rds13/xmlrpc deps/xmlrpc
git clone -- git://github.com/processone/p1_utils deps/p1_utils
git clone -- git://github.com/processone/mysql deps/p1_mysql
git clone -- git://github.com/processone/pgsql deps/p1_pgsql
git clone -- git://github.com/processone/epam deps/p1_pam
git clone -- git://github.com/processone/zlib deps/p1_zlib
git clone -- git://github.com/davisp/jiffy deps/jiffy
git clone -- git://github.com/processone/eiconv deps/p1_iconv
git clone -- git://github.com/cmullaparthi/ibrowse deps/ibrowse
git clone -- git://github.com/esl/lhttpc deps/lhttpc
git clone -- git://github.com/basho/lager deps/lager
git clone -- git://github.com/processone/p1_logger deps/p1_logger
git clone -- git://github.com/DeadZen/goldrush.git deps/goldrush
