# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"
EGIT_REPO_URI="https://github.com/afflux/pure-python-otr.git"

inherit distutils git-2

DESCRIPTION="Off-The-Record Protocol Implementation in Python"
HOMEPAGE="https://github.com/afflux/pure-python-otr.git"

LICENSE="BSD-2"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

