# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"

inherit distutils


DESCRIPTION="PGP packet parser library"
HOMEPAGE="https://github.com/toofishes/python-pgpdump"
SRC_URI="https://github.com/toofishes/python-pgpdump/archive/${PV}.tar.gz"

LICENSE="BSD-2"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""


