# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"

inherit distutils


DESCRIPTION="Python replacement for java.util.Properties."
HOMEPAGE="http://pypi.python.org/pypi/pyjavaproperties"
SRC_URI="https://pypi.python.org/packages/source/p/pyjavaproperties/${P}.tar.gz"

LICENSE="Apache-2.0"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

